### PR TITLE
Fix handling invalid orientation in AutoRotateFilterLoader & test exceptions

### LINKED ISSUE #656: Fix AutoRotateFilterLoader and tests for it
There are 2 issues with `AutoRotateFilterLoader`:

* It fails miserably when an image with an invalid orientation tag is passed (tries to throw `Exception` that doesn't exist in the current namespace (it's not tested with any existing test)

* Tests fail when it falls back to `exif_read_data` due to outdated Imagine (even though class itself handles this case correctly, tests don't account for this case at all, hence [this build fail](https://travis-ci.org/liip/LiipImagineBundle/jobs/88086170))

### PR DESCRIPTION
**Pull request by kamazee**
Fixes #656

### CODE REVIEW

File: Tests/Imagine/Filter/Loader/AutoRotateFilterLoaderTest.php [hunk 1]
```diff
@@ -26,30 +27,42 @@ private function loadExif($exifValue, $expectCallRotateValue, $expectCallFlip)
...
-        // If $exifValue is null, it means the image doesn't contain any metadata.
-        $metaData = $this->getMockMetaData();
+        // Mocks the image and makes it use the fake meta data.
+        $image = $this->getMockImage();
 
-        $metaData
-            ->expects($this->atLeastOnce())
-            ->method('offsetGet')
-            ->willReturn($exifValue);
+        if (method_exists(ImageInterface::class, 'metadata')) {
```
Comment (lsmith77) [inline Tests/Imagine/Filter/Loader/AutoRotateFilterLoaderTest.php]: we still need to be 5.3 friendly

Comment (kamazee) [inline Tests/Imagine/Filter/Loader/AutoRotateFilterLoaderTest.php]: OOPS. Will fix.
